home:
    path: /
    controller: App\Controller\HomeController::index
materia-finder:
    path: /materia-finder
    controller: App\Controller\MateriaFinderController::index
materia-checklist:
    path: /materia-checklist
    controller: App\Controller\MateriaChecklistController::index