#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index
mater-finder:
    path: /materia-finder
    controller: App\Controller\MateriaFinderController::index